insert into  EXCHANGE_VALUE (ID,FROM_CURRENCY,TO_CURRENCY,CONVERSION_MULTIPLE,PORT) VALUES (101,'USD','INR',70,0);
insert into  EXCHANGE_VALUE (ID,FROM_CURRENCY,TO_CURRENCY,CONVERSION_MULTIPLE,PORT) VALUES (102,'EURO','INR',80,0);
insert into  EXCHANGE_VALUE (ID,FROM_CURRENCY,TO_CURRENCY,CONVERSION_MULTIPLE,PORT) VALUES (103,'POUND','INR',90,0);
insert into  EXCHANGE_VALUE (ID,FROM_CURRENCY,TO_CURRENCY,CONVERSION_MULTIPLE,PORT) VALUES (104,'DINAR','INR',100,0);